// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkLuIR83cIqwPV1xZXHWZHPj2j28BRYs',
    appId: '1:935322585762:web:529d5a8b06182329b225fb',
    messagingSenderId: '935322585762',
    projectId: 'testproject-3d2f2',
    authDomain: 'testproject-3d2f2.firebaseapp.com',
    storageBucket: 'testproject-3d2f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtCn1cGmJAWokGMDlXDoeiX6xdrAg0Wfk',
    appId: '1:935322585762:android:f9f537e8986d2413b225fb',
    messagingSenderId: '935322585762',
    projectId: 'testproject-3d2f2',
    storageBucket: 'testproject-3d2f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuJqIpGIRFOLoL8_0aX79LYTFCXvgMDWA',
    appId: '1:935322585762:ios:93787270f7d31677b225fb',
    messagingSenderId: '935322585762',
    projectId: 'testproject-3d2f2',
    storageBucket: 'testproject-3d2f2.firebasestorage.app',
    iosBundleId: 'com.example.installingPackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuJqIpGIRFOLoL8_0aX79LYTFCXvgMDWA',
    appId: '1:935322585762:ios:93787270f7d31677b225fb',
    messagingSenderId: '935322585762',
    projectId: 'testproject-3d2f2',
    storageBucket: 'testproject-3d2f2.firebasestorage.app',
    iosBundleId: 'com.example.installingPackage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnkLuIR83cIqwPV1xZXHWZHPj2j28BRYs',
    appId: '1:935322585762:web:99f990e36fc753dbb225fb',
    messagingSenderId: '935322585762',
    projectId: 'testproject-3d2f2',
    authDomain: 'testproject-3d2f2.firebaseapp.com',
    storageBucket: 'testproject-3d2f2.firebasestorage.app',
  );
}
